// wrap the ACS_* macros with functions

#define NCURSES_OPAQUE 1
#include <curses.h>

#define WRAP(name) \
static inline chtype wrap_ ## name() { \
	return name; \
}

WRAP(ACS_ULCORNER)
WRAP(ACS_LLCORNER)
WRAP(ACS_URCORNER)
WRAP(ACS_LRCORNER)
WRAP(ACS_LTEE)
WRAP(ACS_RTEE)
WRAP(ACS_BTEE)
WRAP(ACS_TTEE)
WRAP(ACS_HLINE)
WRAP(ACS_VLINE)
WRAP(ACS_PLUS)
WRAP(ACS_S1)
WRAP(ACS_S9)
WRAP(ACS_DIAMOND)
WRAP(ACS_CKBOARD)
WRAP(ACS_DEGREE)
WRAP(ACS_PLMINUS)
WRAP(ACS_BULLET)
WRAP(ACS_LARROW)
WRAP(ACS_RARROW)
WRAP(ACS_DARROW)
WRAP(ACS_UARROW)
WRAP(ACS_BOARD)
WRAP(ACS_LANTERN)
WRAP(ACS_BLOCK)
